config/routes.rb
Rails.application.routes.draw do
  namespace :admins do
    get 'orders/index'
    get 'orders/show'
  end
  namespace :admins do
    get 'genres/index'
    get 'genres/edit'
  end
  namespace :admins do
    get 'customers/index'
    get 'customers/show'
    get 'customers/edit'
  end
  namespace :admins do
    get 'products/index'
    get 'products/show'
    get 'products/new'
    get 'products/edit'
  end
  namespace :admins do
    get 'homes/top'
  end
  devise_for :admins
  
  #顧客用サイトのルーティング
  devise_for :customers

  resources :products, only: [:index, :show]


  resources :orders, only: [:new, :index, :create, :show]
    get 'orders/confirm' => 'orders#confirm'
    get 'orders/thanks' => 'orders#thanks'
  resources :order_products, only: [:new, :create, :index, :show]
  resources :cart_items, only: [:index, :create, :update, :destroy] do
    collection do
      delete 'destroy_all'
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :product
  validates :customer_id, presence: true
  validates :product_id, presence: true
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items
  has_many :products, through: :cart_items
  has_many :orders
end

app/models/genre.rb
class Genre < ApplicationRecord
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_products, dependent: :destroy
  has_many :products, :through => :order_items
end

app/models/order_product.rb
class OrderProduct < ApplicationRecord
  belongs_to :order
  belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :genre
  has_many :cart_items
  has_many :customers, through: :cart_items
  has_many :order_products
  attachment :image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController
  before_action :authenticate_customer!
  before_action :set_cart_item, only: [:show, :update, :destroy, :edit]
  before_action :set_customer

  def index
    @cart_items = @customer.cart_items.all
  end

  def create
  end

  def update
  end

  def destroy
  end

  def destroy_all
  end

  private

  def set_customer
    @customer = current_customer
  end

  def set_cart_item
    @cart_item = CartItem.find(params[:id])
  end

  def cart_item_params
    params.require(:cart_item).permit(:product_id, :customer_id, :quantity)
  end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  def edit
  end

  def show
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def confirm
  end

  def index
  end

  def new
  end

  def show
  end

  def thanks
  end

  def create
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
  end

  def show
  end
end

app/helpers/admins/customers_helper.rb
module Admins::CustomersHelper
end

app/helpers/admins/genres_helper.rb
module Admins::GenresHelper
end

app/helpers/admins/homes_helper.rb
module Admins::HomesHelper
end

app/helpers/admins/orders_helper.rb
module Admins::OrdersHelper
end

app/helpers/admins/products_helper.rb
module Admins::ProductsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def price_with_tax(price)
    price = price * 1.08
    "#{price.floor}円"
  end
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/cart_items/index.html.erb
<h1>CartItems#index</h1>
<p>Find me in app/views/cart_items/index.html.erb</p>

<div class="container">
  <div class="row">
    <div class="col-lg-4"><h3>ショッピングカート</h3></div>
    <div class="col-lg-4"><button class="btn btn-danger">カートを空にする</button></div>
  </div>

  <div class="row">
    <div class="col-lg-4"><h5>商品名</h5></div>
    <div class="col-lg-2"><h5>単価（税込）</h5></div>
    <div class="col-lg-2"><h5>数量</h5></div>
    <div class="col-lg-2"><h5>小計</h5></div>
  </div>

<!-- カート内商品一覧 -->
  <% sum_all = 0 %>
  <% @cart_items.each do |cart_item| %>
  <div class="row">
    <div class="col-lg-3">
      <%= link_to product_path(cart_item.product) do%>
      <%= attachment_image_tag(cart_item.product, :image, fallback: "no_img.png", size: "50x50") %>
      <% end %>
    </div>
    <div class="col-lg-2">
      <%= link_to product_path(cart_item.product) do%>
      <%= cart_item.product.name %>
      <% end %>
    </div>
    <div class="col-lg-2">
      <%= price_with_tax(cart_item.product.price) %>
    </div>
    <div class="col-lg-2">
      <%= form_with model: cart_item, local: true do |f| %>
      <%= f.number_field :quantity, value: cart_item.quantity %>
      <%= f.submit "変更", class: "btn btn-primary" %>
      <% end %>
    </div>
    <div class="col-lg-2">
      <%= sum_product = price_with_tax(cart_item.product.price).to_i * cart_item.quantity %>円
      <% sum_all += sum_product %>
    </div>
    <div class="col-lg-1">
      <%= link_to "削除する", cart_item_path(cart_item), method: :delete, class: "btn btn-danger" %>
    </div>
  </div>
  <% end %>

  <!-- 合計金額 + 情報入力ボタン -->
  <div class="row">
    <div class="col-lg-3">
      <%# customer_top_path追加後 %>
      <%# <%= link_to "買い物を続ける", customer_top_path, class:"btn btn-danger" %>
    </div>
    <div class="col-lg-3">
      <div class="row">
        <h5>合計金額：<%= sum_all %>円</h5>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-3">
      <%= link_to "情報入力に進む", new_order_path, class:"btn btn-danger" %>
    </div>
  </div>

</div>